/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface DungeonList {
        "dungeons": any;
    }
    interface FfxivRoute {
        "favorites": string[];
        "freeDest": string;
        "home": string;
    }
    interface FfxivSubroute {
        "data": any;
        "home": any;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDungeonListElement extends Components.DungeonList, HTMLStencilElement {
    }
    var HTMLDungeonListElement: {
        prototype: HTMLDungeonListElement;
        new (): HTMLDungeonListElement;
    };
    interface HTMLFfxivRouteElement extends Components.FfxivRoute, HTMLStencilElement {
    }
    var HTMLFfxivRouteElement: {
        prototype: HTMLFfxivRouteElement;
        new (): HTMLFfxivRouteElement;
    };
    interface HTMLFfxivSubrouteElement extends Components.FfxivSubroute, HTMLStencilElement {
    }
    var HTMLFfxivSubrouteElement: {
        prototype: HTMLFfxivSubrouteElement;
        new (): HTMLFfxivSubrouteElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "dungeon-list": HTMLDungeonListElement;
        "ffxiv-route": HTMLFfxivRouteElement;
        "ffxiv-subroute": HTMLFfxivSubrouteElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface DungeonList {
        "dungeons"?: any;
    }
    interface FfxivRoute {
        "favorites"?: string[];
        "freeDest"?: string;
        "home"?: string;
    }
    interface FfxivSubroute {
        "data"?: any;
        "home"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "dungeon-list": DungeonList;
        "ffxiv-route": FfxivRoute;
        "ffxiv-subroute": FfxivSubroute;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "dungeon-list": LocalJSX.DungeonList & JSXBase.HTMLAttributes<HTMLDungeonListElement>;
            "ffxiv-route": LocalJSX.FfxivRoute & JSXBase.HTMLAttributes<HTMLFfxivRouteElement>;
            "ffxiv-subroute": LocalJSX.FfxivSubroute & JSXBase.HTMLAttributes<HTMLFfxivSubrouteElement>;
        }
    }
}
